In [1]:
# Q1 # 

import numpy as np

x=[[2,3],[1,2]]
y=[[3,4],[5,6]]

print(x)
print(y)

print(np.dot(x,y))

[[2, 3], [1, 2]]
[[3, 4], [5, 6]]
[[21 26]
 [13 16]]


In [2]:
# Q2 # 

import numpy as np

x=[[1,2],[2,3]]
y=[[1,2],[4,5]]

print(np.outer(x,y))


[[ 1  2  4  5]
 [ 2  4  8 10]
 [ 2  4  8 10]
 [ 3  6 12 15]]


In [3]:
# Q3 #

import numpy as np 

x=[[3,4],[5,7]]
y=[[2,3],[6,7]]

print(np.cross(x,y))
print(np.cross(y,x))


[ 1 -7]
[-1  7]


In [5]:
# Q4 #

import numpy as np

x=np.array([[1,2],[3,4]])

print(x)

print(np.linalg.det(x))

[[1 2]
 [3 4]]
-2.0000000000000004


In [ ]:
# Q5 #

import numpy as np



In [13]:
# Q6 #

import numpy as np 

x=np.arange(9).reshape(3,3)
y=np.arange(3,12).reshape(3,3)

z=np.inner(x,y)

print(z)

[[ 14  23  32]
 [ 50  86 122]
 [ 86 149 212]]


In [14]:
# Q7 #

import numpy as np

x=np.array([[1,2],[4,5]])

z,y=np.linalg.eig(x)

print(z)
print(y)

[-0.46410162  6.46410162]
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [15]:
# Q8 #

import numpy as np 

x=np.array([1,2,3])
y=np.array([4,5,6])

print(np.kron(x,y))

[ 4  5  6  8 10 12 12 15 18]


In [16]:
# Q9 #

import numpy as np 

from numpy import linalg as LA 

x=np.array([[2,3,4],[4,5,6]])

print(LA.cond(x))

21.590843464331634


In [18]:
# Q10 #

import numpy as np

x=np.arange(7)

print(np.linalg.norm(x))

y=np.matrix('1,2;4,5')

print(np.linalg.norm(y))


9.539392014169456
6.782329983125268


In [19]:
# Q11 #

import numpy as np

x=np.array([[2,3],[4,5]])

print(np.linalg.det(x))

-2.0


In [20]:
# Q12 # 

import numpy as np 

x=np.array([[3,4],[5,6]])

print(np.linalg.inv(x))

[[-3.   2. ]
 [ 2.5 -1.5]]


In [ ]:
# Q17 #

import numpy as np



In [21]:
# Q13 #

import numpy as np

x=np.array([[3,4],[5,6]])

print(np.linalg.qr(x))

QRResult(Q=array([[-0.51449576, -0.85749293],
       [-0.85749293,  0.51449576]]), R=array([[-5.83095189, -7.20294058],
       [ 0.        , -0.34299717]]))


In [22]:
# Q14 #

import numpy as np 

x=np.array([[2,3],[4,5]])

print(np.linalg.cond(x))

26.9629120178363


In [23]:
# Q15 #

import numpy as np

x=np.arange(6).reshape(2,3)

print(np.trace(x))

4


In [25]:
# Q19 #

import numpy as np 

x=np.arange(9).reshape((3,3))

print(np.linalg.norm(x))

print(np.linalg.cond(x))

14.2828568570857
2.857326358417597e+16
